import { FormEvent, useEffect, useState } from "react";
import { BarChart3, ChevronDown, ChevronUp, Plus, Star, ThumbsUp } from "lucide-react";
import * as api from "../api/reviewApi";

const initial=(postingId:number):api.ReviewInput=>({jobPostingId:postingId,department:"",employmentStatus:"FORMER",tenureMonths:18,rating:4,title:"",pros:"",cons:"",body:"",managementMessage:""});
const polarity:Record<string,string>={POSITIVE:"전반적으로 긍정적",NEUTRAL:"긍정과 부정이 비슷함",NEGATIVE:"개선 의견이 많은 편",MIXED:"상반된 평가가 공존함",PENDING:"분석 집계 중"};
function tenure(months:number){return months>=12?`약 ${Math.floor(months/12)}년${months%12?` ${months%12}개월`:""}`:`약 ${months}개월`}

export function JobPostingReviews({postingId}:{postingId:number}){
 const[data,setData]=useState<api.PostingReviewOverview>(),[open,setOpen]=useState(false),[form,setForm]=useState(()=>initial(postingId));
 const[expanded,setExpanded]=useState<number>(),[error,setError]=useState("");
 const load=()=>api.postingOverview(postingId).then(setData).catch(e=>{if(!String(e.message).includes("404"))setError(e.message)});
 useEffect(()=>{void load()},[postingId]);
 async function submit(e:FormEvent){e.preventDefault();setError("");try{await api.createReview(data!.companyId,form);setForm(initial(postingId));setOpen(false);await load()}catch(x){setError((x as Error).message)}}
 if(!data)return null;const s=data.summary;
 return <section className="job-detail-section posting-reviews">
  <div className="posting-review-heading"><div><span className="eyebrow">WORKPLACE REVIEWS</span><h2>이 회사에서 일해본 사람들의 이야기</h2><p>가상공고와 연결된 완전 창작 리뷰입니다. 감정분석은 전체 리뷰 경향을 참고용으로 집계합니다.</p></div><button className="primary-button" onClick={()=>setOpen(v=>!v)}><Plus size={15}/>리뷰 작성</button></div>
  <div className="review-summary-grid"><div className="review-score"><strong>{s.averageRating.toFixed(1)}</strong><span>{Array.from({length:5},(_,i)=><Star key={i} size={18} fill={i<Math.round(s.averageRating)?"currentColor":"none"}/>)}</span><small>리뷰 {s.reviewCount}개</small></div><div className="review-sentiment"><span><BarChart3 size={16}/>종합 감정분석</span><strong>{polarity[s.dominantPolarity]??"분석 집계 중"}</strong><div className="sentiment-bar"><i style={{width:`${s.positive*100}%`}}/><i style={{width:`${s.neutral*100}%`}}/><i style={{width:`${s.negative*100}%`}}/></div><small>긍정 {Math.round(s.positive*100)} · 중립 {Math.round(s.neutral*100)} · 부정 {Math.round(s.negative*100)} / 분석 {s.analyzedCount}건</small></div><div className="review-emotions"><span>자주 나타난 감정</span><div>{s.topEmotions.length?s.topEmotions.map(e=><b key={e.label}>{e.label}</b>):<small>분석 결과를 모으는 중입니다.</small>}</div></div></div>
  {open&&<form className="posting-review-form" onSubmit={submit}><div className="review-form-title"><div><span className="eyebrow">WRITE A REVIEW</span><h3>솔직한 근무 경험 남기기</h3></div><button type="button" className="icon-button" aria-label="리뷰 작성 닫기" onClick={()=>setOpen(false)}>×</button></div><div className="review-form-row"><label>소속 조직<input required maxLength={150} placeholder="예: 백엔드 개발팀" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>재직 상태<select value={form.employmentStatus} onChange={e=>setForm({...form,employmentStatus:e.target.value as "CURRENT"|"FORMER"})}><option value="CURRENT">재직 중</option><option value="FORMER">퇴사</option></select></label><label>재직 기간<span className="month-input"><input type="number" min={1} max={600} value={form.tenureMonths} onChange={e=>setForm({...form,tenureMonths:+e.target.value})}/><small>개월</small></span></label></div><fieldset className="star-field"><legend>총점</legend>{[1,2,3,4,5].map(n=><button type="button" aria-label={`${n}점`} key={n} className={n<=form.rating?"active":""} onClick={()=>setForm({...form,rating:n})}><Star size={22} fill="currentColor"/></button>)}</fieldset>{([['title','한줄평','성장은 하지만 운영 체계는 더 필요했어요',200],['pros','장점','구체적으로 좋았던 제도와 경험을 적어주세요.',900],['cons','아쉬운 점','공고와 달랐거나 개선이 필요한 점을 적어주세요.',900],['body','상세 경험','담당 업무, 팀 문화, 실제 근무 경험을 설명해 주세요.',1500],['managementMessage','경영진에게 바라는 점','회사에 개선을 제안한다면 무엇인가요?',900]] as const).map(([key,label,placeholder,maxLength])=><label className="review-copy-field" key={key}>{label}<textarea required placeholder={placeholder} maxLength={maxLength} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/><small>{form[key].length.toLocaleString()} / {maxLength.toLocaleString()}자</small></label>)}<button className="primary-button" type="submit">리뷰 등록</button></form>}
  {error&&<p className="form-error">{error}</p>}
  <div className="posting-review-list">{data.reviews.map(r=><article key={r.id}><header><div><b>{r.displayAuthor}</b><span>{r.department} · {r.employmentStatus==="FORMER"?"퇴사":"재직 중"} · {tenure(r.tenureMonths)}</span></div><div className="review-stars">{Array.from({length:5},(_,i)=><Star key={i} size={14} fill={i<r.rating?"currentColor":"none"}/>)}</div></header><h3>{r.title}</h3><div className="review-points"><div><b>좋았던 점</b><p>{r.pros}</p></div><div><b>아쉬운 점</b><p>{r.cons}</p></div></div>{expanded===r.id&&<div className="review-expanded"><p>{r.body}</p><blockquote><b>경영진에게 바라는 점</b>{r.managementMessage}</blockquote></div>}<footer><button onClick={()=>setExpanded(v=>v===r.id?undefined:r.id)}>{expanded===r.id?<ChevronUp size={14}/>:<ChevronDown size={14}/>}상세 {expanded===r.id?"접기":"보기"}</button><button onClick={()=>api.likeReview(r.id).then(v=>setData(d=>d&&({...d,reviews:d.reviews.map(x=>x.id===r.id?{...x,likeCount:v.count}:x)}))).catch(e=>setError(e.message))}><ThumbsUp size={14}/>도움돼요 {r.likeCount??0}</button></footer></article>)}</div>
 </section>
}
