import { FormEvent, useEffect, useState } from "react";
import { emptyCareerProfile, type CareerProfile } from "../model/careerProfile.types";

export function CareerProfileForm({ initial, onSave, onCancel, saveLabel = "정보 저장하기" }: { initial?: CareerProfile; onSave: (value: CareerProfile) => Promise<void>; onCancel?: () => void; saveLabel?: string }) {
  const [form, setForm] = useState<CareerProfile>(initial ?? emptyCareerProfile()); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (initial) setForm(initial); }, [initial]);
  const set = <K extends keyof CareerProfile>(key: K, value: CareerProfile[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(""); setSaving(true); try { await onSave(form); } catch (reason) { setError(reason instanceof Error ? reason.message : "저장에 실패했습니다."); } finally { setSaving(false); } };
  return <form className="career-profile-form" onSubmit={submit}><div className="form-section"><h3>희망 직무</h3><div className="form-fields"><label>목표 직무*<input required maxLength={80} value={form.targetRole} onChange={(e) => set("targetRole", e.target.value)} placeholder="예: 백엔드 개발자" /></label><label>직무 분야*<input required maxLength={80} value={form.targetJobFamily} onChange={(e) => set("targetJobFamily", e.target.value)} /></label><label>희망 지역<input value={form.preferredLocations.join(", ")} onChange={(e) => set("preferredLocations", e.target.value.split(",").map((v) => v.trim()).filter(Boolean))} placeholder="서울, 경기" /></label><label>입사 가능일<input type="date" value={form.availableFrom ?? ""} onChange={(e) => set("availableFrom", e.target.value || null)} /></label><label>경력 구분<select value={form.experienceType} onChange={(e) => set("experienceType", e.target.value)}><option value="ENTRY">신입</option><option value="EXPERIENCED">경력</option><option value="ANY">무관</option></select></label><label>총 경력 개월<input type="number" min={0} value={form.totalCareerMonths} onChange={(e) => set("totalCareerMonths", Number(e.target.value))} /></label></div></div><div className="form-section"><h3>학력 및 역량</h3><div className="form-fields"><label>최종 학력<select value={form.educationLevel ?? ""} onChange={(e) => set("educationLevel", e.target.value || null)}><option value="">선택 안 함</option><option value="HIGH_SCHOOL">고등학교</option><option value="COLLEGE">전문대</option><option value="BACHELOR">대학교</option><option value="MASTER">대학원</option></select></label><label>학교명<input value={form.schoolName ?? ""} onChange={(e) => set("schoolName", e.target.value || null)} /></label><label>전공<input value={form.major ?? ""} onChange={(e) => set("major", e.target.value || null)} /></label><label>졸업 상태<select value={form.graduationStatus ?? ""} onChange={(e) => set("graduationStatus", e.target.value || null)}><option value="">선택 안 함</option><option value="GRADUATED">졸업</option><option value="EXPECTED">졸업 예정</option><option value="ENROLLED">재학</option></select></label><label>GitHub 아이디<input value={form.githubUsername ?? ""} onChange={(e) => set("githubUsername", e.target.value || null)} /></label><label>포트폴리오 URL<input type="url" value={form.portfolioUrl ?? ""} onChange={(e) => set("portfolioUrl", e.target.value || null)} /></label><label className="wide">기술·프로젝트 요약<textarea rows={4} value={form.technicalSummary ?? ""} onChange={(e) => set("technicalSummary", e.target.value || null)} placeholder="Java, Spring Boot 프로젝트 경험과 담당 역할 등을 적어주세요." /></label></div></div>{error && <div className="auth-error">{error}</div>}<div className="form-actions">{onCancel && <button type="button" className="outline-button" onClick={onCancel}>취소</button>}<button className="primary-button" disabled={saving}>{saving ? "저장 중..." : saveLabel}</button></div></form>;
}
