import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, MessageCircle, Send, ThumbsUp } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import * as api from "../features/community/api/communityApi";
import type { Comment, Post } from "../features/community/api/communityApi";

export function CommunityDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const postId = Number(id);
  const [post, setPost] = useState<Post | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [body, setBody] = useState("");
  const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [editedBody, setEditedBody] = useState("");
  const [editingCommentId, setEditingCommentId] = useState<number | null>(null); const [commentBody, setCommentBody] = useState(""); const [deleting, setDeleting] = useState(false); const [error, setError] = useState("");
  const refreshComments = () => api.comments(postId).then(setComments);
  const load = () => { void api.detail(postId).then((item) => { setPost(item); setTitle(item.title); setEditedBody(item.body); }).catch((e) => setError(e instanceof Error ? e.message : "게시글을 불러오지 못했습니다.")); void refreshComments(); };
  useEffect(load, [postId]);
  const submitComment = async (event: FormEvent) => { event.preventDefault(); if (!body.trim()) return; await api.comment(postId, body); setBody(""); await refreshComments(); };
  if (error) return <section className="community-detail-page"><Link className="community-back-link" to="/community"><ArrowLeft size={16} />목록으로</Link><p className="form-error">{error}</p></section>;
  if (!post) return <section className="community-detail-page">게시글을 불러오는 중입니다.</section>;
  return <section className="community-detail-page"><Link className="community-back-link" to="/community"><ArrowLeft size={16} />목록으로</Link>
    {editing ? <form className="community-editor" onSubmit={async (event) => { event.preventDefault(); const saved = await api.update(post.id, { boardType: post.boardType, title, body: editedBody, serviceFeedback: post.serviceFeedback, privatePost: post.privatePost }); setPost(saved); setEditing(false); }}><label>제목<input value={title} onChange={(event) => setTitle(event.target.value)} required maxLength={200} /></label><label>내용<textarea value={editedBody} onChange={(event) => setEditedBody(event.target.value)} required maxLength={5000} /></label><div className="form-actions"><button className="outline-button" type="button" onClick={() => setEditing(false)}>취소</button><button className="primary-button">수정 저장</button></div></form> : <article className="community-post-detail"><span className="community-post-category">{post.boardType === "FREE" ? "자유게시판" : "Q&A 게시판"}</span><h1>{post.title}</h1><small>{post.author} · {new Date(post.createdAt).toLocaleString("ko-KR")}</small><p>{post.body}</p><div className="community-detail-actions"><button onClick={async () => { await api.like(post.id); load(); }}><ThumbsUp size={15} />좋아요 {post.likes}</button>{post.mine && <><button onClick={() => setEditing(true)}>수정</button><button className="danger" onClick={() => setDeleting(true)}>삭제</button></>}</div>{deleting && <div className="community-inline-confirm"><span>이 글을 삭제할까요?</span><button className="outline-button" onClick={() => setDeleting(false)}>취소</button><button className="danger" onClick={async () => { await api.remove(post.id); navigate("/community"); }}>삭제</button></div>}</article>}
    <section className="community-comments"><h2><MessageCircle size={18} />댓글 {comments.length}</h2>{comments.map((item) => <article key={item.id}><strong>{item.author}</strong><small>{new Date(item.createdAt).toLocaleString("ko-KR")}</small>{editingCommentId === item.id ? <form className="community-comment-edit" onSubmit={async (event) => { event.preventDefault(); if (!commentBody.trim()) return; await api.updateComment(item.id, commentBody); setEditingCommentId(null); await refreshComments(); }}><textarea value={commentBody} onChange={(event) => setCommentBody(event.target.value)} maxLength={2000} /><button className="primary-button">저장</button><button type="button" onClick={() => setEditingCommentId(null)}>취소</button></form> : <><p>{item.body}</p><button onClick={async () => { await api.likeComment(item.id); await refreshComments(); }}><ThumbsUp size={13} /> {item.likes}</button>{item.mine && <><button onClick={() => { setEditingCommentId(item.id); setCommentBody(item.body); }}>수정</button><button className="danger" onClick={async () => { if (confirm("이 댓글을 삭제할까요?")) { await api.removeComment(item.id); await refreshComments(); } }}>삭제</button></>}</>}</article>)}<form className="community-comment-editor" onSubmit={submitComment}><textarea value={body} onChange={(event) => setBody(event.target.value)} maxLength={2000} placeholder="댓글을 입력하세요" /><button className="primary-button"><Send size={14} />등록</button></form></section>
  </section>;
}
