import { FormEvent,useEffect,useState } from "react";
import { MessageCircle,ThumbsUp } from "lucide-react";
import { PageHeading } from "../shared/components/PageHeading";
import * as api from "../features/community/api/communityApi";
const empty=(boardType:api.Board):api.Input=>({boardType,title:"",body:"",serviceFeedback:false,privatePost:false});
export function CommunityPage(){
 const[board,setBoard]=useState<api.Board>("FREE"),[posts,setPosts]=useState<api.Post[]>([]),[selected,setSelected]=useState<api.Post>();
 const[comments,setComments]=useState<api.Comment[]>([]),[form,setForm]=useState(empty("FREE")),[comment,setComment]=useState(""),[query,setQuery]=useState(""),[sort,setSort]=useState("RECENT"),[error,setError]=useState("");
 const load=()=>api.list(board,query,sort).then(setPosts).catch(e=>setError(e.message));
 useEffect(()=>{setForm(empty(board));setSelected(undefined);void load()},[board,sort]);
 async function open(id:number){try{setSelected(await api.detail(id));setComments(await api.comments(id))}catch(e){setError((e as Error).message)}}
 async function submit(e:FormEvent){e.preventDefault();try{await api.create(form);setForm(empty(board));await load()}catch(x){setError((x as Error).message)}}
 async function addComment(e:FormEvent){e.preventDefault();if(!selected)return;await api.comment(selected.id,comment);setComment("");setComments(await api.comments(selected.id))}
 async function report(target:"POST"|"COMMENT",id:number){const reason=prompt("신고 사유를 입력하세요");if(reason)try{await api.report(target,id,reason);alert("신고가 접수되었습니다.")}catch(e){setError((e as Error).message)}}
 return <><PageHeading eyebrow="COMMUNITY" title="자유게시판 · Q&A" body="일반 대화와 홈페이지 서비스 피드백을 구분해 운영합니다."/>
 <div className="ranking-tabs"><button className={board==="FREE"?"active":""} onClick={()=>setBoard("FREE")}>자유게시판</button><button className={board==="QNA"?"active":""} onClick={()=>setBoard("QNA")}>Q&A</button></div>{error&&<p className="form-error">{error}</p>}
 <div className="community-toolbar"><form onSubmit={e=>{e.preventDefault();void load()}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="제목·내용 검색"/><button>검색</button></form><select value={sort} onChange={e=>setSort(e.target.value)}><option value="RECENT">최신순</option><option value="POPULAR">조회순</option><option value="LIKED">좋아요순</option></select></div>
 <div className="community-layout"><section><form className="panel review-form" onSubmit={submit}><h3>새 글 작성</h3><input required maxLength={200} placeholder="제목" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required maxLength={5000} placeholder="내용" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><label><input type="checkbox" checked={form.serviceFeedback} onChange={e=>setForm({...form,serviceFeedback:e.target.checked})}/> 홈페이지 기능·사용 경험에 대한 피드백입니다</label>{board==="QNA"&&<label><input type="checkbox" checked={form.privatePost} onChange={e=>setForm({...form,privatePost:e.target.checked})}/> 비공개 문의</label>}<button className="primary-button">등록</button></form>
 <div className="community-list">{posts.map(p=><button className="panel" key={p.id} onClick={()=>open(p.id)}><span>{p.privatePost?"🔒 ":""}{p.title}</span><small>{p.author} · 조회 {p.views} · 좋아요 {p.likes}</small></button>)}</div></section>
 <aside>{selected?<article className="panel community-detail"><h2>{selected.title}</h2><small>{selected.author} · {new Date(selected.createdAt).toLocaleString("ko-KR")}</small><p>{selected.body}</p>{selected.serviceFeedback&&<span className="eyebrow">서비스 피드백 분석 대상</span>}<div><button onClick={async()=>{await api.like(selected.id);await open(selected.id)}}><ThumbsUp size={15}/> {selected.likes}</button>{!selected.mine&&<button onClick={()=>report("POST",selected.id)}>신고</button>}{selected.mine&&<><button onClick={async()=>{const title=prompt("제목 수정",selected.title),body=prompt("내용 수정",selected.body);if(title&&body){await api.update(selected.id,{boardType:selected.boardType,title,body,serviceFeedback:selected.serviceFeedback,privatePost:selected.privatePost});await open(selected.id);await load()}}}>수정</button><button onClick={async()=>{await api.remove(selected.id);setSelected(undefined);await load()}}>삭제</button></>}</div><hr/><h3><MessageCircle size={17}/> 댓글</h3>
 {comments.map(c=><div className="community-comment" style={{marginLeft:c.parentId?24:0}} key={c.id}><b>{c.author}</b><p>{c.body}</p><button onClick={async()=>{await api.likeComment(c.id);setComments(await api.comments(selected.id))}}>좋아요 {c.likes}</button>{!c.mine&&<button onClick={()=>report("COMMENT",c.id)}>신고</button>}{c.mine&&<><button onClick={async()=>{const body=prompt("댓글 수정",c.body);if(body){await api.updateComment(c.id,body);setComments(await api.comments(selected.id))}}}>수정</button><button onClick={async()=>{await api.removeComment(c.id);setComments(await api.comments(selected.id))}}>삭제</button></>}</div>)}
 <form onSubmit={addComment}><textarea required maxLength={2000} value={comment} onChange={e=>setComment(e.target.value)} placeholder="댓글을 입력하세요"/><button>댓글 등록</button></form></article>:<div className="panel data-empty">글을 선택하면 내용을 볼 수 있습니다.</div>}</aside></div></>}
