import { ArrowLeft, Heart, MapPin, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getEmployerTalent, getEmployerTalentFavorites, toggleEmployerTalentFavorite, type EmployerTalent } from "../features/employer/api/employerTalentApi";
import { DataStatePanel } from "../shared/components/DataStatePanel";

const entryLabel: Record<string, string> = { EDUCATION: "학력", CAREER: "경력", ACTIVITY: "인턴 · 대외활동", TRAINING: "교육이수", AWARD: "수상", LANGUAGE: "어학", OVERSEAS: "해외경험", PORTFOLIO: "프로젝트 · 포트폴리오", PREFERENCE: "기타 스펙" };
export function EmployerTalentDetailPage() {
  const { memberId } = useParams(); const [talent, setTalent] = useState<EmployerTalent | null>(null); const [favorite, setFavorite] = useState(false); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { if (!memberId) return; void Promise.all([getEmployerTalent(Number(memberId)), getEmployerTalentFavorites()]).then(([item, favorites]) => { setTalent(item); setFavorite(favorites.some((value) => value.memberId === item.memberId)); setStatus("ready"); }).catch(() => setStatus("error")); }, [memberId]);
  if (status === "loading") return <DataStatePanel state="loading" />;
  if (status === "error" || !talent) return <><Link className="job-detail-back" to="/employer/dashboard"><ArrowLeft size={16} />인재 대시보드</Link><DataStatePanel state="error" errorTitle="인재 정보를 불러오지 못했습니다" errorBody="회원이 비공개로 전환했거나 일시적인 오류가 발생했습니다." /></>;
  const toggle = () => void toggleEmployerTalentFavorite(talent.memberId).then((result) => setFavorite(result.favorite));
  return <div className="employer-talent-detail-page"><Link className="job-detail-back" to="/employer/dashboard"><ArrowLeft size={16} />인재 대시보드</Link><section className="panel talent-detail-hero"><div className="talent-detail-avatar">{talent.profilePhotoDataUrl ? <img src={talent.profilePhotoDataUrl} alt={`${talent.nickname} 프로필 사진`} /> : <UserRound size={30} />}</div><div><span className="eyebrow">PUBLIC TALENT PROFILE</span><h1>{talent.nickname} 님의 공개 스펙</h1><p>{talent.targetJobFamily} · {talent.targetRole}</p></div><button type="button" className={`talent-detail-favorite ${favorite ? "active" : ""}`} onClick={toggle}><Heart size={17} fill={favorite ? "currentColor" : "none"} />{favorite ? "관심 인재" : "관심 인재로 저장"}</button></section><div className="talent-detail-grid"><section className="panel"><h2>기본 정보</h2><dl><div><dt>희망 직무</dt><dd>{talent.targetJobFamily} · {talent.targetRole}</dd></div><div><dt>경력</dt><dd>{talent.experienceType === "ENTRY" ? "신입" : `${talent.totalCareerMonths}개월 경력`}</dd></div><div><dt>희망 지역</dt><dd><MapPin size={15} />{talent.preferredLocations}</dd></div></dl></section><section className="panel"><h2>기술 스택</h2><div className="talent-skill-tags">{talent.skills.length ? talent.skills.map((skill) => <span key={skill}>{skill}</span>) : "등록한 기술이 없습니다."}</div></section><section className="panel talent-detail-summary"><h2>기술 요약</h2><p>{talent.technicalSummary || "등록한 기술 요약이 없습니다."}</p>{talent.portfolioUrl && <a href={talent.portfolioUrl} target="_blank" rel="noreferrer">포트폴리오 보기</a>}</section><section className="panel talent-detail-full"><h2>경험 · 이력 · 프로젝트</h2>{talent.entries.length ? <div className="talent-record-list">{talent.entries.map((entry, index) => <article key={`${entry.type}-${entry.title}-${index}`}><span>{entryLabel[entry.type] ?? entry.type}</span><strong>{entry.title}</strong>{entry.detail && <p>{entry.detail}</p>}</article>)}</div> : <p className="empty-state">공개한 학력, 경력, 프로젝트 또는 활동 정보가 없습니다.</p>}</section><section className="panel talent-detail-full"><h2>자격증</h2>{talent.certificates.length ? <div className="talent-record-list">{talent.certificates.map((item) => <article key={item.name}><strong>{item.name}</strong><p>{[item.issuer, item.acquiredAt].filter(Boolean).join(" · ")}</p></article>)}</div> : <p className="empty-state">공개한 자격증 정보가 없습니다.</p>}</section><section className="panel talent-detail-full"><h2>자기소개서</h2>{talent.selfIntroductions.length ? <div className="talent-record-list">{talent.selfIntroductions.map((item, index) => <article key={`${item.title}-${index}`}><span>{item.primary ? "대표 자기소개서" : "자기소개서"}</span><strong>{item.title}</strong><p>{item.content}</p></article>)}</div> : <p className="empty-state">공개한 자기소개서가 없습니다.</p>}</section></div></div>;
}
