import { FormEvent, useEffect, useState } from "react";
import { Bookmark, ChevronRight, Heart, KeyRound, MessageCircle, Pencil, Target, UserX } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";
import { changeNickname, changePassword, withdraw } from "../features/auth/api/accountApi";
import { useAuth } from "../features/auth/model/AuthContext";
import { getBookmarkedJobs } from "../features/interests/api/interestsApi";
import { getBookmarkedOpportunities, toggleOpportunityInterest } from "../features/opportunities/api/opportunityInterestsApi";
import { OpportunityCard } from "../features/opportunities/components/OpportunityCard";
import type { Opportunity } from "../features/opportunities/model/opportunity.types";
import { useInterests } from "../features/interests/model/InterestContext";
import { JobPostingCard } from "../features/job-postings/components/JobPostingCard";
import type { JobPosting } from "../features/job-postings/model/jobPosting.types";
import { SubscriptionSection } from "../features/subscription/components/SubscriptionSection";
import { PushNotificationSection } from "../features/push-notifications/components/PushNotificationSection";
import { PageHeading } from "../shared/components/PageHeading";
import { SavedCapabilityList } from "./CapabilityManagementPage";
import { getCertificateBookmarks, removeCertificateBookmark, type QnetQualification } from "../features/profile/api/memberCertificatesApi";
import { CertificateDetailModal } from "../features/profile/components/CertificateDetailModal";
import { like, likeComment, myActivities, type CommunityActivity } from "../features/community/api/communityApi";
import { getTalentVisibility, setTalentVisibility } from "../features/profile/api/talentVisibilityApi";

type Action = "nickname" | "password" | "withdraw" | null;
type Menu = "account" | "capability" | "activity" | "saved" | "subscription";
const menuItems: Array<[Menu, string]> = [["account", "내 계정"], ["capability", "나의 스펙"], ["activity", "커뮤니티 활동"], ["saved", "찜 목록"], ["subscription", "이용권 · 알림"]];

export function MyPage() {
  const { member, loading, updateMember, logout } = useAuth(); const { interestCount, interestIds } = useInterests(); const navigate = useNavigate(); const location = useLocation();
  const [menu, setMenu] = useState<Menu>("account"); const [action, setAction] = useState<Action>(null); const [nickname, setNickname] = useState(member?.nickname ?? ""); const [passwords, setPasswords] = useState({ current: "", next: "" }); const [withdrawPassword, setWithdrawPassword] = useState("");
  const [activities, setActivities] = useState<CommunityActivity[]>([]); const [jobs, setJobs] = useState<JobPosting[]>([]); const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [certificates, setCertificates] = useState<QnetQualification[]>([]); const [certificateDetail, setCertificateDetail] = useState<QnetQualification | null>(null); const [talentPublic, setTalentPublic] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState<Action>(null);
  useEffect(() => { void getBookmarkedJobs().then(setJobs).catch(() => setJobs([])); }, [interestCount]);
  useEffect(() => { void getBookmarkedOpportunities().then(setOpportunities).catch(() => setOpportunities([])); void getCertificateBookmarks().then(setCertificates).catch(() => setCertificates([])); void getTalentVisibility().then((v) => setTalentPublic(v.enabled)).catch(() => {}); }, []);
  const refreshActivities = () => myActivities().then((data) => setActivities(data.items)).catch(() => setActivities([])); useEffect(() => { if (member) void refreshActivities(); }, [member]);
  useEffect(() => { if (!loading && !member) navigate(`/login?returnTo=${encodeURIComponent(`${location.pathname}${location.search}`)}`, { replace: true }); }, [loading, member, navigate, location.pathname, location.search]);
  const run = async (kind: Exclude<Action, null>, work: () => Promise<void>, success: string) => { if (submitting) return; setError(""); setMessage(""); setSubmitting(kind); try { await work(); setMessage(success); setAction(null); } catch (e) { setError(e instanceof Error ? e.message : "요청에 실패했습니다."); } finally { setSubmitting(null); } };
  const changeVisibility = () => { const next = !talentPublic; if (window.confirm(next ? "기업에게 내 역량을 공개할까요?" : "기업에게 내 역량 공개를 해제할까요?")) void setTalentVisibility(next).then((v) => setTalentPublic(v.enabled)); };
  const cancelLike = async (item: CommunityActivity) => { if (item.type === "POST_LIKE") await like(item.targetId); if (item.type === "COMMENT_LIKE") await likeComment(item.targetId); await refreshActivities(); };
  if (!member) return null; const bookmarked = jobs.filter((job) => interestIds.includes(job.id));
  return <><PageHeading eyebrow="MY ACCOUNT" title="마이페이지" body="메뉴를 선택해 내 정보와 활동을 편하게 관리하세요." />{(message || error) && <div className={error ? "account-alert error" : "account-alert"}>{error || message}</div>}<div className="mypage-menu-layout"><nav className="mypage-menu" aria-label="마이페이지 메뉴">{menuItems.map(([key, label]) => <button key={key} type="button" className={menu === key ? "active" : ""} onClick={() => setMenu(key)}>{label}<ChevronRight size={15} /></button>)}</nav><div className="mypage-menu-content">
    {menu === "account" && <><section className="panel account-summary"><div className="avatar large">{member.nickname.slice(0, 1)}</div><div><h2>{member.nickname}</h2><p>{member.loginId} · {member.email}</p></div></section><section className="account-actions"><button onClick={() => setAction(action === "nickname" ? null : "nickname")}><Pencil size={18} /><span><strong>닉네임 변경</strong><small>서비스에 표시되는 이름을 변경합니다.</small></span><ChevronRight size={17} /></button><button onClick={() => setAction(action === "password" ? null : "password")}><KeyRound size={18} /><span><strong>비밀번호 변경</strong><small>안전한 계정 관리를 위해 변경합니다.</small></span><ChevronRight size={17} /></button><button className="withdraw-action" onClick={() => setAction(action === "withdraw" ? null : "withdraw")}><UserX size={18} /><span><strong>회원 탈퇴</strong><small>회원 정보와 일정이 삭제됩니다.</small></span><ChevronRight size={17} /></button></section>{action === "nickname" && <section className="panel account-editor"><h2>닉네임 변경</h2><form onSubmit={(e: FormEvent) => { e.preventDefault(); void run("nickname", async () => updateMember(await changeNickname(nickname.trim())), "닉네임을 변경했습니다."); }}><label>새 닉네임<input required minLength={2} maxLength={80} value={nickname} onChange={(e) => setNickname(e.target.value)} /></label><button className="primary-button" disabled={submitting === "nickname"}>변경하기</button></form></section>}{action === "password" && <section className="panel account-editor"><h2>비밀번호 변경</h2><form onSubmit={(e: FormEvent) => { e.preventDefault(); void run("password", () => changePassword(passwords.current, passwords.next), "비밀번호를 변경했습니다."); }}><label>현재 비밀번호<input required type="password" value={passwords.current} onChange={(e) => setPasswords({ ...passwords, current: e.target.value })} /></label><label>새 비밀번호<input required type="password" minLength={8} value={passwords.next} onChange={(e) => setPasswords({ ...passwords, next: e.target.value })} /></label><button className="primary-button" disabled={submitting === "password"}>변경하기</button></form></section>}{action === "withdraw" && <section className="panel account-editor danger-zone"><h2>회원 탈퇴</h2><form onSubmit={(e: FormEvent) => { e.preventDefault(); if (confirm("회원 정보와 일정이 모두 삭제됩니다. 정말 탈퇴할까요?")) void run("withdraw", async () => { await withdraw(withdrawPassword); logout(); navigate("/login", { replace: true }); }, ""); }}><label>비밀번호 확인<input required type="password" value={withdrawPassword} onChange={(e) => setWithdrawPassword(e.target.value)} /></label><button className="danger-button" disabled={submitting === "withdraw"}>회원 탈퇴 진행</button></form></section>}</>}
    {menu === "capability" && <><div className="mypage-section-title"><div><h2>나의 스펙정보</h2><p>저장한 역량과 공개 설정을 관리합니다.</p></div><button className="outline-button" onClick={() => navigate("/capability?tool=profile")}><Target size={16} />스펙정보 입력</button></div><section className="panel mypage-capability-view"><SavedCapabilityList readOnly /></section><section className="panel talent-visibility-setting"><div><strong>기업에게 내 역량 공개</strong><p>{talentPublic ? "현재 기업이 내 공개 스펙을 조회할 수 있습니다." : "현재 기업에게 내 스펙이 표시되지 않습니다."}</p></div><button type="button" className={`visibility-switch ${talentPublic ? "on" : ""}`} role="switch" aria-checked={talentPublic} onClick={changeVisibility}><span /></button></section></>}
    {menu === "activity" && <><div className="saved-jobs-title"><div><MessageCircle size={18} /><h2>커뮤니티 활동</h2></div><span>{activities.length}건</span></div><section className="panel community-activity-list">{activities.length === 0 ? <div className="saved-empty">작성한 글, 댓글 또는 좋아요 활동이 없습니다.</div> : activities.map((item) => <article key={`${item.type}-${item.targetId}-${item.createdAt}`}><button type="button" className="community-activity-open" onClick={() => navigate(`/community/${item.postId ?? item.targetId}`)}>{item.type.includes("LIKE") ? <Heart size={15} /> : <MessageCircle size={15} />}<div><strong>{{ POST: "작성한 글", COMMENT: "작성한 댓글", POST_LIKE: "글 좋아요", COMMENT_LIKE: "댓글 좋아요" }[item.type]}</strong><span>{item.title}</span><small>{new Date(item.createdAt).toLocaleString("ko-KR")}</small></div></button>{item.type.includes("LIKE") ? <button className="outline-button" onClick={() => void cancelLike(item)}>좋아요 취소</button> : <button className="outline-button" onClick={() => navigate(`/community/${item.postId ?? item.targetId}`)}>관리</button>}</article>)}</section></>}
    {menu === "saved" && <><div className="saved-jobs-title"><div><Bookmark size={18} /><h2>찜한 채용공고</h2></div><span>{bookmarked.length}개</span></div>{bookmarked.length ? <section className="posting-grid">{bookmarked.map((job) => <JobPostingCard key={job.id} posting={job} />)}</section> : <section className="panel saved-empty">찜한 채용공고가 없습니다.</section>}<div className="saved-jobs-title"><div><Bookmark size={18} /><h2>찜한 자격증</h2></div><span>{certificates.length}개</span></div>{certificates.length ? <section className="certificate-opportunity-grid">{certificates.map((item) => <article className="certificate-opportunity-card" key={item.code}><div><strong>{item.name}</strong><span>{[item.qualificationType, item.field].filter(Boolean).join(" · ")}</span></div><div className="certificate-opportunity-actions"><button onClick={() => setCertificateDetail(item)}>시험 일정</button><button className="bookmark active" onClick={() => void removeCertificateBookmark(item.code).then(setCertificates)}><Bookmark size={17} fill="currentColor" /></button></div></article>)}</section> : <section className="panel saved-empty">찜한 자격증이 없습니다.</section>}<div className="saved-jobs-title"><div><Bookmark size={18} /><h2>찜한 성장 기회</h2></div><span>{opportunities.length}개</span></div>{opportunities.length ? <section className="opportunity-grid">{opportunities.map((item) => <OpportunityCard key={item.id} item={item} interested onInterest={() => void toggleOpportunityInterest(item.id, false).then(() => setOpportunities((current) => current.filter((value) => value.id !== item.id)))} />)}</section> : <section className="panel saved-empty">찜한 성장 기회가 없습니다.</section>}</>}
    {menu === "subscription" && <><SubscriptionSection /><PushNotificationSection /></>}
  </div></div>{certificateDetail && <CertificateDetailModal item={certificateDetail} onClose={() => setCertificateDetail(null)} />}</>;
}
