package com.jobpilot.api.domain.review.service;
import com.jobpilot.api.domain.admin.AdminAccessService;import com.jobpilot.api.domain.employer.service.EmployerAccessService;import com.jobpilot.api.domain.jobposting.repository.JobPostingRepository;import com.jobpilot.api.global.exception.ResourceNotFoundException;import java.time.LocalDateTime;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service public class ReviewOperationsService{private final JdbcTemplate db;private final AdminAccessService admins;private final EmployerAccessService employers;private final JobPostingRepository postings;public ReviewOperationsService(JdbcTemplate db,AdminAccessService admins,EmployerAccessService employers,JobPostingRepository postings){this.db=db;this.admins=admins;this.employers=employers;this.postings=postings;}
 @Transactional public Map<String,Object> like(long review,Long member){visible(review);int d=db.update("DELETE FROM company_review_likes WHERE review_id=? AND member_id=?",review,member);if(d==0)db.update("INSERT INTO company_review_likes(review_id,member_id) VALUES (?,?)",review,member);Long count=db.queryForObject("SELECT COUNT(*) FROM company_review_likes WHERE review_id=?",Long.class,review);return Map.of("liked",d==0,"count",count==null?0:count);}
 @Transactional public void report(long review,Long member,String reason){visible(review);if(reason==null||reason.isBlank()||reason.strip().length()>1000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"신고 사유를 입력하세요.");try{db.update("INSERT INTO company_review_reports(review_id,member_id,reason) VALUES (?,?,?)",review,member,reason.strip());}catch(org.springframework.dao.DuplicateKeyException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"이미 신고한 리뷰입니다.");}}
 public List<Map<String,Object>> reports(Long admin){admins.requireAdmin(admin);return db.queryForList("SELECT rp.id,rp.review_id,rp.reason,rp.status,r.title,r.display_author,r.visibility,rp.created_at FROM company_review_reports rp JOIN company_reviews r ON r.id=rp.review_id WHERE rp.status='OPEN' ORDER BY rp.id DESC");}
 @Transactional public void moderate(Long admin,long review,String action,String reason){admins.requireAdmin(admin);if(!List.of("HIDE","RESTORE","DELETE","REANALYZE").contains(action))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"관리 작업이 올바르지 않습니다.");if(reason==null||reason.isBlank()||reason.length()>1000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"관리 사유가 필요합니다.");visibleOrHidden(review);if("REANALYZE".equals(action))db.update("UPDATE company_reviews SET analysis_state='PENDING',analysis_attempts=0,next_analysis_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND visibility='PUBLIC'",review);else{String state="RESTORE".equals(action)?"PUBLIC":"DELETE".equals(action)?"DELETED":"HIDDEN";db.update("UPDATE company_reviews SET visibility=?,next_analysis_at=IF(?='PUBLIC',next_analysis_at,NULL),updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?",state,state,review);}db.update("INSERT INTO company_review_moderation_events(review_id,admin_member_id,action,reason) VALUES (?,?,?,?)",review,admin,action,reason.strip());db.update("UPDATE company_review_reports SET status='RESOLVED' WHERE review_id=? AND status='OPEN'",review);}
 public Map<String,Object> employerSummary(Long employer,long posting){employers.requireApproved(employer);postings.findByIdAndEmployerAccountId(posting,employer).orElseThrow(()->new ResourceNotFoundException("내 공고를 찾을 수 없습니다."));Map<String,Object> totals=db.queryForMap("""
  SELECT COUNT(*) reviewCount,COALESCE(AVG(r.rating),0) averageRating,SUM(r.rating=1) rating1,SUM(r.rating=2) rating2,SUM(r.rating=3) rating3,SUM(r.rating=4) rating4,SUM(r.rating=5) rating5,
   SUM(a.polarity='POSITIVE') positiveCount,SUM(a.polarity='NEUTRAL') neutralCount,SUM(a.polarity='NEGATIVE') negativeCount,SUM(a.polarity='MIXED') mixedCount,SUM(a.id IS NULL) pendingCount
  FROM company_reviews r LEFT JOIN company_review_analyses a ON a.id=(SELECT a2.id FROM company_review_analyses a2 WHERE a2.review_id=r.id AND a2.content_hash=r.content_hash ORDER BY a2.analyzed_at DESC,a2.id DESC LIMIT 1) WHERE r.job_posting_id=? AND r.visibility='PUBLIC'
  """,posting);List<Map<String,Object>> emotions=db.queryForList("""
  SELECT jt.label,AVG(jt.score) averageScore,COUNT(*) occurrences FROM company_review_analyses a JOIN company_reviews r ON r.id=a.review_id AND r.content_hash=a.content_hash AND a.id=(SELECT a2.id FROM company_review_analyses a2 WHERE a2.review_id=r.id AND a2.content_hash=r.content_hash ORDER BY a2.analyzed_at DESC,a2.id DESC LIMIT 1),
  JSON_TABLE(a.emotions,'$[*]' COLUMNS(label VARCHAR(100) PATH '$.label',score DOUBLE PATH '$.score')) jt
  WHERE r.job_posting_id=? AND r.visibility='PUBLIC' GROUP BY jt.label ORDER BY averageScore DESC,occurrences DESC LIMIT 10
  """,posting);return Map.of("summary",totals,"topEmotions",emotions,"sampleWarning",((Number)totals.get("reviewCount")).longValue()<5);}
 private void visible(long id){Integer n=db.queryForObject("SELECT COUNT(*) FROM company_reviews WHERE id=? AND visibility='PUBLIC'",Integer.class,id);if(n==null||n==0)throw new ResourceNotFoundException("리뷰를 찾을 수 없습니다.");}private void visibleOrHidden(long id){Integer n=db.queryForObject("SELECT COUNT(*) FROM company_reviews WHERE id=? AND visibility<>'DELETED'",Integer.class,id);if(n==null||n==0)throw new ResourceNotFoundException("리뷰를 찾을 수 없습니다.");}
}
