import { type ReactNode, useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Minus, Plus } from "lucide-react";
import { createResumeEntry, deleteResumeEntry, listResumeEntries, updateResumeEntry } from "../api/resumeEntriesApi";
import type { ResumeEntry, ResumeEntryInput, ResumeEntryType } from "../model/resumeEntry.types";

type Field = { key: string; label: string; kind?: "date" | "url" | "textarea" };
type Section = { type: ResumeEntryType; id: string; title: string; fields: Field[] };
const sections: Section[] = [
  { type: "PERSONAL", id: "resume-personal", title: "인적사항", fields: [{ key: "name", label: "성명(한글)" }, { key: "hanjaName", label: "성명(한자)" }, { key: "birthDate", label: "생년월일", kind: "date" }, { key: "email", label: "이메일" }, { key: "phone", label: "휴대전화" }, { key: "address", label: "주소" }] },
  { type: "EDUCATION", id: "resume-education", title: "학력", fields: [{ key: "school", label: "학교명" }, { key: "major", label: "전공" }, { key: "degree", label: "학위/학력" }, { key: "status", label: "졸업 상태" }, { key: "startedAt", label: "입학일", kind: "date" }, { key: "endedAt", label: "졸업일", kind: "date" }, { key: "grade", label: "학점" }] },
  { type: "CAREER", id: "resume-career", title: "경력", fields: [{ key: "company", label: "회사명" }, { key: "department", label: "부서" }, { key: "position", label: "직급/직책" }, { key: "startedAt", label: "입사일", kind: "date" }, { key: "endedAt", label: "퇴사일", kind: "date" }, { key: "description", label: "담당 업무·성과", kind: "textarea" }] },
  { type: "ACTIVITY", id: "resume-activity", title: "인턴 · 대외활동", fields: [{ key: "activityType", label: "활동 유형" }, { key: "organization", label: "기관/주최" }, { key: "startedAt", label: "시작일", kind: "date" }, { key: "endedAt", label: "종료일", kind: "date" }, { key: "description", label: "활동 내용", kind: "textarea" }] },
  { type: "TRAINING", id: "resume-training", title: "교육이수", fields: [{ key: "provider", label: "교육기관" }, { key: "startedAt", label: "시작일", kind: "date" }, { key: "endedAt", label: "종료일", kind: "date" }, { key: "description", label: "교육 내용", kind: "textarea" }] },
  { type: "AWARD", id: "resume-award", title: "수상", fields: [{ key: "organization", label: "수여기관" }, { key: "awardedAt", label: "수상일", kind: "date" }, { key: "description", label: "수상 내용", kind: "textarea" }] },
  { type: "OVERSEAS", id: "resume-overseas", title: "해외경험", fields: [{ key: "country", label: "국가" }, { key: "startedAt", label: "시작일", kind: "date" }, { key: "endedAt", label: "종료일", kind: "date" }, { key: "description", label: "경험 내용", kind: "textarea" }] },
  { type: "LANGUAGE", id: "resume-language", title: "어학", fields: [{ key: "language", label: "외국어" }, { key: "exam", label: "시험명" }, { key: "score", label: "점수/등급" }, { key: "acquiredAt", label: "취득일", kind: "date" }] },
  { type: "PORTFOLIO", id: "resume-portfolio", title: "포트폴리오", fields: [{ key: "linkType", label: "링크 유형" }, { key: "url", label: "URL", kind: "url" }, { key: "description", label: "설명", kind: "textarea" }] },
  { type: "PREFERENCE", id: "resume-preference", title: "취업우대 · 병역", fields: [{ key: "preferenceType", label: "구분" }, { key: "status", label: "상태/내용" }, { key: "description", label: "상세", kind: "textarea" }] },
];
const navItems = [
  { id: "resume-personal", title: "인적사항", add: false },
  { id: "resume-desired-role", title: "희망직무", add: false }, { id: "resume-skills", title: "스킬", add: false },
  ...sections.slice(1, 5).map(({ id, title, type }) => ({ id, title, type, add: true })),
  { id: "resume-certificates", title: "자격증", add: false },
  ...sections.slice(5).map(({ id, title, type }) => ({ id, title, type, add: true })),
  { id: "resume-self-introduction", title: "자기소개서", add: false },
];
const blank = (section: Section, order: number): ResumeEntryInput => ({ entryType: section.type, title: section.type === "PERSONAL" ? "인적사항" : "", content: Object.fromEntries(section.fields.map((field) => [field.key, ""])), displayOrder: order });

export function ResumeEntryEditor({ profileEditor, selfIntroduction }: { profileEditor?: ReactNode; selfIntroduction?: ReactNode }) {
  const [entries, setEntries] = useState<ResumeEntry[]>([]); const [drafts, setDrafts] = useState<Record<string, ResumeEntryInput>>({}); const [editingIds, setEditingIds] = useState<Record<string, number | null>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [navOpen, setNavOpen] = useState(true); const [loaded, setLoaded] = useState(false);
  useEffect(() => { void listResumeEntries().then(setEntries).catch(() => setMessage("상세 이력 정보를 불러오지 못했습니다.")).finally(() => setLoaded(true)); }, []);
  useEffect(() => { if (loaded && !entries.some((entry) => entry.entryType === "PERSONAL")) add(sections[0]); }, [loaded, entries]);
  const byType = useMemo(() => new Map(sections.map((section) => [section.type, entries.filter((entry) => entry.entryType === section.type)])), [entries]);
  const add = (section: Section) => { setEditingIds((current) => ({ ...current, [section.type]: null })); setDrafts((current) => ({ ...current, [section.type]: blank(section, (byType.get(section.type) ?? []).length) })); };
  const edit = (entry: ResumeEntry) => { setEditingIds((current) => ({ ...current, [entry.entryType]: entry.id })); setDrafts((current) => ({ ...current, [entry.entryType]: { entryType: entry.entryType, title: entry.title, content: { ...entry.content }, displayOrder: entry.displayOrder } })); };
  const clear = (type: ResumeEntryType) => { setEditingIds((current) => { const next = { ...current }; delete next[type]; return next; }); setDrafts((current) => { const next = { ...current }; delete next[type]; return next; }); };
  const save = async (section: Section, entry?: ResumeEntry) => { const draft = drafts[section.type]; if (!draft?.title.trim()) return setMessage(`${section.title} 제목을 입력해 주세요.`); setBusy(true); try { const saved = entry ? await updateResumeEntry(entry.id, draft) : await createResumeEntry(draft); setEntries((current) => [...current.filter((value) => value.id !== saved.id), saved].sort((a, b) => a.entryType.localeCompare(b.entryType) || a.displayOrder - b.displayOrder || a.id - b.id)); clear(section.type); setMessage("임시 저장했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "저장에 실패했습니다."); } finally { setBusy(false); } };
  const remove = async (entry: ResumeEntry) => { if (!confirm("이 항목을 삭제할까요?")) return; setBusy(true); try { await deleteResumeEntry(entry.id); setEntries((current) => current.filter((value) => value.id !== entry.id)); } catch (error) { setMessage(error instanceof Error ? error.message : "삭제에 실패했습니다."); } finally { setBusy(false); } };
  const removeLatest = (section: Section) => { const latest = [...(byType.get(section.type) ?? [])].at(-1); if (latest) void remove(latest); };
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  const renderSection = (section: Section) => { const items = byType.get(section.type) ?? []; const draft = drafts[section.type]; const personal = section.type === "PERSONAL"; return <section className="jobkorea-entry-section" id={section.id} key={section.type}><div className="jobkorea-entry-title"><h3>{section.title}{personal && <small className="required-label">필수</small>}</h3>{!personal && <button type="button" className="text-button" onClick={() => add(section)}><Plus size={15} /> {section.title} 추가</button>}</div>{items.map((entry) => <EntryCard key={entry.id} section={section} entry={entry} draft={editingIds[section.type] === entry.id ? draft : null} busy={busy} personal={personal} onEdit={() => edit(entry)} onDelete={() => void remove(entry)} onChange={(next) => setDrafts((current) => ({ ...current, [section.type]: next }))} onSave={() => void save(section, entry)} onCancel={() => clear(section.type)} />)}{draft && editingIds[section.type] === null && <EntryCard section={section} entry={null} draft={draft} busy={busy} personal={personal} onEdit={() => undefined} onDelete={() => undefined} onChange={(next) => setDrafts((current) => ({ ...current, [section.type]: next }))} onSave={() => void save(section)} onCancel={() => clear(section.type)} />}{!personal && items.length === 0 && !draft && <button type="button" className="jobkorea-empty-add" onClick={() => add(section)}><Plus size={16} /> {section.title} 추가</button>}</section>; };
  return <div className="jobkorea-resume-layout"><div className="jobkorea-resume-main"><div className="resume-entry-heading"><div><span className="eyebrow">RESUME EDITOR</span><h2>이력 항목</h2><p>중앙에서 내용을 작성하고, 우측 목록에서 원하는 항목으로 바로 이동하거나 추가할 수 있습니다.</p></div></div>{message && <p className="resume-document-message">{message}</p>}{renderSection(sections[0])}{profileEditor}{sections.slice(1).map(renderSection)}{selfIntroduction}</div>
    <div className="jobkorea-nav-wrap"><button className="jobkorea-nav-toggle" type="button" onClick={() => setNavOpen((current) => !current)} aria-expanded={navOpen}>{navOpen ? <ChevronRight size={16} /> : <ChevronLeft size={16} />} 이력서 항목</button>{navOpen && <aside className="jobkorea-resume-nav" aria-label="이력서 항목"><strong>이력서 항목</strong>{navItems.map((item) => <div className="jobkorea-nav-row" key={item.id}><button type="button" onClick={() => go(item.id)}>{item.title}</button>{item.add && "type" in item && (() => { const section = sections.find((value) => value.type === item.type); const hasItem = section && (byType.get(section.type) ?? []).length > 0; return <span><button aria-label={hasItem ? `${item.title} 마지막 항목 삭제` : `${item.title} 추가`} type="button" disabled={busy} onClick={() => { if (!section) return; if (hasItem) removeLatest(section); else { go(section.id); add(section); } }}>{hasItem ? <Minus size={15} /> : <Plus size={15} />}</button></span>; })()}</div>)}</aside>}</div></div>;
}

function EntryCard({ section, entry, draft, busy, personal, onEdit, onDelete, onChange, onSave, onCancel }: { section: Section; entry: ResumeEntry | null; draft: ResumeEntryInput | null; busy: boolean; personal: boolean; onEdit: () => void; onDelete: () => void; onChange: (value: ResumeEntryInput) => void; onSave: () => void; onCancel: () => void }) {
  if (!draft) return <article className="jobkorea-entry-card"><div><strong>{entry?.title}</strong><p>{section.fields.map((field) => entry?.content[field.key]).filter(Boolean).join(" · ") || "입력해 주세요"}</p></div><div className="form-actions"><button type="button" className="outline-button" onClick={onEdit}>수정</button>{!personal && <button type="button" className="outline-button danger-button" disabled={busy} onClick={onDelete}><Minus size={13} /> 삭제</button>}</div></article>;
  const set = (key: string, value: string) => onChange({ ...draft, content: { ...draft.content, [key]: value } });
  return <article className="jobkorea-entry-card editing"><div className="form-fields">{!personal && <label className="wide">{section.title}명*<input value={draft.title} onChange={(event) => onChange({ ...draft, title: event.target.value })} /></label>}{section.fields.map((field) => <label className={field.kind === "textarea" ? "wide" : ""} key={field.key}>{field.label}{field.kind === "textarea" ? <textarea rows={3} value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)} /> : <input type={field.kind ?? "text"} value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)} />}</label>)}</div><div className="form-actions">{!personal && <button type="button" className="outline-button" onClick={onCancel}>취소</button>}<button type="button" className="primary-button" disabled={busy} onClick={onSave}>{busy ? "저장 중…" : "임시저장"}</button></div></article>;
}
