import { type ReactNode, useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Minus, Plus, X } from "lucide-react";
import { PostcodeSearchModal } from "../../location-jobs/components/PostcodeSearchModal";
import { createResumeEntry, deleteResumeEntry, listResumeEntries, updateResumeEntry } from "../api/resumeEntriesApi";
import type { ResumeEntry, ResumeEntryInput, ResumeEntryType } from "../model/resumeEntry.types";

type Field = { key: string; label: string; kind?: "date" | "url" | "textarea" | "select"; options?: string[] };
type Section = { type: ResumeEntryType; id: string; title: string; fields: Field[] };
const sections: Section[] = [
  { type: "PERSONAL", id: "resume-personal", title: "인적사항", fields: [{ key: "name", label: "성명(한글)" }, { key: "hanjaName", label: "성명(한자)" }, { key: "birthDate", label: "생년월일", kind: "date" }, { key: "email", label: "이메일" }, { key: "phone", label: "휴대전화" }, { key: "address", label: "주소" }] },
  { type: "EDUCATION", id: "resume-education", title: "학력", fields: [{ key: "school", label: "학교명" }, { key: "major", label: "전공" }, { key: "degree", label: "학위/학력" }, { key: "status", label: "졸업 상태" }, { key: "startedAt", label: "입학일", kind: "date" }, { key: "endedAt", label: "졸업일", kind: "date" }, { key: "grade", label: "학점" }] },
  { type: "CAREER", id: "resume-career", title: "경력", fields: [{ key: "company", label: "회사명" }, { key: "department", label: "부서" }, { key: "position", label: "직급/직책" }, { key: "startedAt", label: "입사일", kind: "date" }, { key: "endedAt", label: "퇴사일", kind: "date" }, { key: "description", label: "담당 업무·성과", kind: "textarea" }] },
  { type: "ACTIVITY", id: "resume-activity", title: "인턴 · 대외활동", fields: [{ key: "activityType", label: "활동 유형" }, { key: "organization", label: "기관/주최" }, { key: "startedAt", label: "시작일", kind: "date" }, { key: "endedAt", label: "종료일", kind: "date" }, { key: "description", label: "활동 내용", kind: "textarea" }] },
  { type: "TRAINING", id: "resume-training", title: "교육이수", fields: [{ key: "provider", label: "교육기관" }, { key: "startedAt", label: "시작일", kind: "date" }, { key: "endedAt", label: "종료일", kind: "date" }, { key: "description", label: "교육 내용", kind: "textarea" }] },
  { type: "AWARD", id: "resume-award", title: "수상", fields: [{ key: "organization", label: "수여기관" }, { key: "awardedAt", label: "수상일", kind: "date" }, { key: "description", label: "수상 내용", kind: "textarea" }] },
  { type: "LANGUAGE", id: "resume-language", title: "어학", fields: [{ key: "language", label: "외국어" }, { key: "exam", label: "시험명" }, { key: "score", label: "점수/등급" }, { key: "acquiredAt", label: "취득일", kind: "date" }] },
  { type: "PORTFOLIO", id: "resume-portfolio", title: "포트폴리오", fields: [{ key: "linkType", label: "링크 유형" }, { key: "url", label: "URL", kind: "url" }, { key: "description", label: "설명", kind: "textarea" }] },
  { type: "PREFERENCE", id: "resume-preference", title: "병역사항", fields: [{ key: "serviceType", label: "병역 구분", kind: "select", options: ["군필", "복무중", "면제", "미필", "해당없음"] }, { key: "branch", label: "군별" }, { key: "rank", label: "계급" }, { key: "startedAt", label: "입대일", kind: "date" }, { key: "endedAt", label: "전역일", kind: "date" }, { key: "description", label: "상세", kind: "textarea" }] },
];
type NavItem = { id: string; title: string; type?: ResumeEntryType; add: boolean; certificate?: boolean };
const navItems: NavItem[] = [
  { id: "resume-personal", title: "인적사항", add: false },
  { id: "resume-desired-role", title: "희망직무", add: false },
  ...sections.filter(({ type }) => ["EDUCATION", "TRAINING"].includes(type)).map(({ id, title, type }) => ({ id, title, type, add: true })),
  { id: "resume-skills", title: "스킬", add: false },
  ...sections.filter(({ type }) => ["CAREER", "ACTIVITY"].includes(type)).map(({ id, title, type }) => ({ id, title, type, add: true })),
  { id: "resume-certificates", title: "자격증", add: true, certificate: true },
  ...sections.filter(({ type }) => ["AWARD", "LANGUAGE", "PORTFOLIO", "PREFERENCE"].includes(type)).map(({ id, title, type }) => ({ id, title, type, add: true })),
  { id: "resume-self-introduction", title: "자기소개서", add: false },
];
const blank = (section: Section, order: number): ResumeEntryInput => ({ entryType: section.type, title: section.type === "PERSONAL" ? "인적사항" : "", content: Object.fromEntries(section.fields.map((field) => [field.key, ""])), displayOrder: order });

export function ResumeEntryEditor({ profileEditor, selfIntroduction, certificateCount = 0, onCertificateAction, onSaveState }: { profileEditor?: ReactNode; selfIntroduction?: ReactNode; certificateCount?: number; onCertificateAction?: (action: "add" | "remove") => void; onSaveState?: (status: "DRAFT" | "SAVED") => Promise<unknown> }) {
  const [entries, setEntries] = useState<ResumeEntry[]>([]); const [drafts, setDrafts] = useState<Record<string, ResumeEntryInput>>({}); const [editingIds, setEditingIds] = useState<Record<string, number | null>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [navOpen, setNavOpen] = useState(true); const [loaded, setLoaded] = useState(false);
  useEffect(() => { void listResumeEntries().then(setEntries).catch(() => setMessage("상세 이력 정보를 불러오지 못했습니다.")).finally(() => setLoaded(true)); }, []);
  useEffect(() => { if (loaded && !entries.some((entry) => entry.entryType === "PERSONAL")) add(sections[0]); }, [loaded, entries]);
  const byType = useMemo(() => new Map(sections.map((section) => [section.type, entries.filter((entry) => entry.entryType === section.type)])), [entries]);
  const hasContent = (value: Pick<ResumeEntryInput, "title" | "content">) => Boolean(value.title.trim() || Object.values(value.content).some((item) => String(item ?? "").trim()));
  const confirmDiscard = (value: Pick<ResumeEntryInput, "title" | "content">) => !hasContent(value) || confirm("작성중이던 내용이 있습니다. 정말로 삭제하시겠습니까?");
  const add = (section: Section) => { setEditingIds((current) => ({ ...current, [section.type]: null })); setDrafts((current) => ({ ...current, [section.type]: blank(section, (byType.get(section.type) ?? []).length) })); };
  const edit = (entry: ResumeEntry) => { setEditingIds((current) => ({ ...current, [entry.entryType]: entry.id })); setDrafts((current) => ({ ...current, [entry.entryType]: { entryType: entry.entryType, title: entry.title, content: { ...entry.content }, displayOrder: entry.displayOrder } })); };
  const clear = (type: ResumeEntryType) => { setEditingIds((current) => { const next = { ...current }; delete next[type]; return next; }); setDrafts((current) => { const next = { ...current }; delete next[type]; return next; }); };
  const save = async (section: Section, entry?: ResumeEntry) => { const draft = drafts[section.type]; if (!draft?.title.trim()) return setMessage(`${section.title} 제목을 입력해 주세요.`); setBusy(true); try { const saved = entry ? await updateResumeEntry(entry.id, draft) : await createResumeEntry(draft); setEntries((current) => [...current.filter((value) => value.id !== saved.id), saved].sort((a, b) => a.entryType.localeCompare(b.entryType) || a.displayOrder - b.displayOrder || a.id - b.id)); clear(section.type); setMessage("임시 저장했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "저장에 실패했습니다."); } finally { setBusy(false); } };
  const remove = async (entry: ResumeEntry) => { if (!confirmDiscard(entry)) return; setBusy(true); try { await deleteResumeEntry(entry.id); setEntries((current) => current.filter((value) => value.id !== entry.id)); } catch (error) { setMessage(error instanceof Error ? error.message : "삭제에 실패했습니다."); } finally { setBusy(false); } };
  const removeLatest = (section: Section) => { const latest = [...(byType.get(section.type) ?? [])].at(-1); if (latest) void remove(latest); };
  const saveAll = async (finalSave: boolean) => {
    const pending = Object.values(drafts); if (pending.length === 0) { try { await onSaveState?.(finalSave ? "SAVED" : "DRAFT"); setMessage(finalSave ? "이력서 전체를 저장했습니다." : "이력서 전체를 임시 저장했습니다."); } catch { setMessage("저장 상태를 기록하지 못했습니다."); } return; }
    const invalid = pending.find((draft) => !draft.title.trim()); if (invalid) return setMessage("추가한 항목의 제목을 입력해 주세요.");
    setBusy(true); try {
      const saved = await Promise.all(pending.map((draft) => { const editingId = editingIds[draft.entryType]; return editingId ? updateResumeEntry(editingId, draft) : createResumeEntry(draft); }));
      setEntries((current) => [...current.filter((entry) => !saved.some((value) => value.id === entry.id)), ...saved].sort((a, b) => a.entryType.localeCompare(b.entryType) || a.displayOrder - b.displayOrder || a.id - b.id));
      await onSaveState?.(finalSave ? "SAVED" : "DRAFT"); setDrafts({}); setEditingIds({}); setMessage(finalSave ? "이력서 전체를 저장했습니다." : "이력서 전체를 임시 저장했습니다.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "저장에 실패했습니다."); } finally { setBusy(false); }
  };
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  const renderSection = (section: Section) => { const items = byType.get(section.type) ?? []; const draft = drafts[section.type]; const personal = section.type === "PERSONAL"; const closeDraft = () => { if (draft && confirmDiscard(draft)) clear(section.type); }; return <section className="jobkorea-entry-section" id={section.id} key={section.type}><div className="jobkorea-entry-title"><h3>{section.title}{personal && <small className="required-label">필수</small>}</h3></div>{items.map((entry) => <EntryCard key={entry.id} section={section} entry={entry} draft={editingIds[section.type] === entry.id ? draft : null} busy={busy} personal={personal} onEdit={() => edit(entry)} onDelete={() => void remove(entry)} onCloseDraft={closeDraft} onChange={(next) => setDrafts((current) => ({ ...current, [section.type]: next }))} />)}{draft && editingIds[section.type] === null && <EntryCard section={section} entry={null} draft={draft} busy={busy} personal={personal} onEdit={() => undefined} onDelete={() => undefined} onCloseDraft={closeDraft} onChange={(next) => setDrafts((current) => ({ ...current, [section.type]: next }))} />}{!personal && !draft && <button type="button" className="jobkorea-empty-add" onClick={() => add(section)}><Plus size={16} /> {section.title} 추가</button>}</section>; };
  return <div className="jobkorea-resume-layout"><div className="jobkorea-resume-main"><div className="resume-entry-heading"><div><span className="eyebrow">RESUME EDITOR</span><h2>이력 항목</h2><p>중앙에서 내용을 작성하고, 우측 목록에서 원하는 항목으로 바로 이동하거나 추가할 수 있습니다.</p></div></div>{message && <p className="resume-document-message">{message}</p>}{renderSection(sections[0])}{profileEditor}{sections.slice(1).map(renderSection)}{selfIntroduction}</div>
    <div className="jobkorea-nav-wrap"><button className="jobkorea-nav-toggle" type="button" onClick={() => setNavOpen((current) => !current)} aria-expanded={navOpen}>{navOpen ? <ChevronRight size={16} /> : <ChevronLeft size={16} />} 이력서 항목</button>{navOpen && <aside className="jobkorea-resume-nav" aria-label="이력서 항목"><strong>이력서 항목</strong>{navItems.map((item) => { const section = item.type ? sections.find((value) => value.type === item.type) : undefined; const active = item.certificate ? certificateCount > 0 : Boolean(section && ((byType.get(section.type) ?? []).length > 0 || drafts[section.type])); const addItem = () => { if (item.certificate) { go(item.id); onCertificateAction?.("add"); return; } if (!section) return; go(section.id); if (!drafts[section.type]) add(section); }; const removeItem = () => { if (item.certificate) { go(item.id); onCertificateAction?.("remove"); return; } if (!section) return; const draft = drafts[section.type]; if (draft) { if (confirmDiscard(draft)) clear(section.type); } else removeLatest(section); }; return <div className={`jobkorea-nav-row ${item.add ? (active ? "is-active" : "is-empty") : ""}`} key={item.id}><button type="button" onClick={() => go(item.id)}>{item.title}</button>{item.add && <span><button aria-label={`${item.title} 추가`} type="button" disabled={busy} onClick={addItem}><Plus size={15} /></button>{active && <button aria-label={`${item.title} 삭제`} type="button" disabled={busy} onClick={removeItem}><Minus size={15} /></button>}</span>}</div>; })}<div className="jobkorea-save-actions"><button type="button" className="outline-button" disabled={busy} onClick={() => void saveAll(false)}>임시저장</button><button type="button" className="primary-button" disabled={busy} onClick={() => void saveAll(true)}>저장하기</button></div></aside>}</div></div>;
}

function EntryCard({ section, entry, draft, busy, personal, onEdit, onDelete, onCloseDraft, onChange }: { section: Section; entry: ResumeEntry | null; draft: ResumeEntryInput | null; busy: boolean; personal: boolean; onEdit: () => void; onDelete: () => void; onCloseDraft: () => void; onChange: (value: ResumeEntryInput) => void }) {
  if (!draft) return <article className="jobkorea-entry-card"><div><strong>{entry?.title}</strong><p>{section.fields.map((field) => entry?.content[field.key]).filter(Boolean).join(" · ") || "입력해 주세요"}</p></div><div className="form-actions"><button type="button" className="outline-button" onClick={onEdit}>수정</button>{!personal && <button type="button" className="outline-button danger-button" disabled={busy} onClick={onDelete}><Minus size={13} /> 삭제</button>}</div></article>;
  const set = (key: string, value: string) => onChange({ ...draft, content: { ...draft.content, [key]: value } });
  return <article className="jobkorea-entry-card editing"><button type="button" className="jobkorea-entry-close" aria-label={`${section.title} 작성 닫기`} title="닫기" onClick={onCloseDraft}><X size={18} /></button><div className="form-fields">{!personal && <label className="wide">{section.title}명*<input value={draft.title} onChange={(event) => onChange({ ...draft, title: event.target.value })} /></label>}{section.fields.map((field) => field.key === "address" && personal ? <AddressInput key={field.key} value={draft.content[field.key] ?? ""} onChange={(value) => set(field.key, value)} /> : <label className={field.kind === "textarea" ? "wide" : ""} key={field.key}>{field.label}{field.kind === "textarea" ? <textarea rows={3} value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)} /> : field.kind === "select" ? <select value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)}><option value="">선택 안 함</option>{field.options?.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input type={field.kind ?? "text"} value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)} />}</label>)}</div></article>;
}

function AddressInput({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const [open, setOpen] = useState(false);
  return <label className="wide">주소<div className="address-search-field"><input value={value} readOnly placeholder="주소 검색을 눌러 선택해 주세요" /><button type="button" className="outline-button" onClick={() => setOpen(true)}>주소 검색</button></div><PostcodeSearchModal isOpen={open} onClose={() => setOpen(false)} onSelectAddress={onChange} /></label>;
}
