import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronUp, Pencil, Plus, Trash2 } from "lucide-react";
import { createResumeEntry, deleteResumeEntry, listResumeEntries, updateResumeEntry } from "../api/resumeEntriesApi";
import type { ResumeEntry, ResumeEntryInput, ResumeEntryType } from "../model/resumeEntry.types";

type Field = { key: string; label: string; kind?: "date" | "url" | "textarea" };
type Section = { type: ResumeEntryType; title: string; help: string; fields: Field[] };
const sections: Section[] = [
  { type: "EDUCATION", title: "학력", help: "학교·전공·학위와 재학 상태를 여러 건 저장합니다.", fields: [{ key: "school", label: "학교명" }, { key: "major", label: "전공" }, { key: "degree", label: "학위/학력" }, { key: "status", label: "졸업 상태" }, { key: "startedAt", label: "입학일", kind: "date" }, { key: "endedAt", label: "졸업일", kind: "date" }, { key: "grade", label: "학점 (선택)" }] },
  { type: "CAREER", title: "경력", help: "회사·직무·기간과 실제 담당 업무 및 성과를 작성합니다.", fields: [{ key: "company", label: "회사명" }, { key: "department", label: "부서" }, { key: "position", label: "직급/직책" }, { key: "startedAt", label: "입사일", kind: "date" }, { key: "endedAt", label: "퇴사일", kind: "date" }, { key: "employmentStatus", label: "재직 상태" }, { key: "description", label: "담당 업무·성과", kind: "textarea" }] },
  { type: "ACTIVITY", title: "인턴 · 대외활동 · 교육", help: "유형과 기관, 기간 및 본인의 역할을 기록합니다.", fields: [{ key: "activityType", label: "활동 유형" }, { key: "organization", label: "기관/주최" }, { key: "startedAt", label: "시작일", kind: "date" }, { key: "endedAt", label: "종료일", kind: "date" }, { key: "description", label: "활동 내용", kind: "textarea" }] },
  { type: "AWARD", title: "수상", help: "수상명과 주최기관, 수상 근거를 관리합니다.", fields: [{ key: "organization", label: "수여기관" }, { key: "awardedAt", label: "수상일", kind: "date" }, { key: "description", label: "수상 내용", kind: "textarea" }] },
  { type: "LANGUAGE", title: "어학", help: "시험·점수·취득일을 필요할 때만 추가하세요.", fields: [{ key: "language", label: "외국어" }, { key: "exam", label: "시험명" }, { key: "score", label: "점수/등급" }, { key: "acquiredAt", label: "취득일", kind: "date" }] },
  { type: "PORTFOLIO", title: "포트폴리오 · 기타문서", help: "GitHub, 배포 주소, Notion, 블로그 등 여러 링크를 저장합니다.", fields: [{ key: "linkType", label: "링크 유형" }, { key: "url", label: "URL", kind: "url" }, { key: "description", label: "설명", kind: "textarea" }] },
];

const blank = (section: Section): ResumeEntryInput => ({ entryType: section.type, title: "", content: Object.fromEntries(section.fields.map((field) => [field.key, ""])), displayOrder: 0 });

export function ResumeEntryEditor() {
  const [entries, setEntries] = useState<ResumeEntry[]>([]); const [open, setOpen] = useState<ResumeEntryType | null>("EDUCATION");
  const [draft, setDraft] = useState<ResumeEntryInput | null>(null); const [editingId, setEditingId] = useState<number | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void listResumeEntries().then(setEntries).catch(() => setMessage("상세 이력 정보를 불러오지 못했습니다.")); }, []);
  const byType = useMemo(() => new Map(sections.map((section) => [section.type, entries.filter((entry) => entry.entryType === section.type)])), [entries]);
  const begin = (section: Section, entry?: ResumeEntry) => { setOpen(section.type); setEditingId(entry?.id ?? null); setDraft(entry ? { entryType: entry.entryType, title: entry.title, content: { ...entry.content }, displayOrder: entry.displayOrder } : blank(section)); setMessage(""); };
  const save = async () => { if (!draft || !draft.title.trim()) return setMessage("제목을 입력해 주세요."); setBusy(true); try { const saved = editingId ? await updateResumeEntry(editingId, draft) : await createResumeEntry(draft); setEntries((current) => [...current.filter((entry) => entry.id !== saved.id), saved].sort((a, b) => a.entryType.localeCompare(b.entryType) || a.displayOrder - b.displayOrder || a.id - b.id)); setDraft(null); setEditingId(null); setMessage("이력 항목을 저장했습니다."); } catch (error) { setMessage(error instanceof Error ? error.message : "저장에 실패했습니다."); } finally { setBusy(false); } };
  const remove = async (id: number) => { if (!confirm("이 이력 항목을 삭제할까요?")) return; setBusy(true); try { await deleteResumeEntry(id); setEntries((current) => current.filter((entry) => entry.id !== id)); } catch (error) { setMessage(error instanceof Error ? error.message : "삭제에 실패했습니다."); } finally { setBusy(false); } };
  return <section className="resume-entry-editor"><div className="resume-entry-heading"><div><span className="eyebrow">DETAILED RESUME</span><h2>상세 이력</h2><p>필요한 항목만 열어 여러 건을 추가하고, 저장한 내용은 이력서 초안과 AI 첨삭의 근거로 사용됩니다.</p></div><span className="resume-entry-count">{entries.length}개 저장됨</span></div>{message && <p className="resume-document-message">{message}</p>}
    {sections.map((section) => { const items = byType.get(section.type) ?? []; const expanded = open === section.type; return <article className={`resume-entry-section ${expanded ? "open" : ""}`} key={section.type}><button type="button" className="resume-entry-section-head" onClick={() => setOpen(expanded ? null : section.type)}><span><strong>{section.title}</strong><small>{section.help}</small></span><b>{items.length}</b>{expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button>{expanded && <div className="resume-entry-section-body">{items.map((entry) => <div className="resume-entry-row" key={entry.id}><div><strong>{entry.title}</strong><p>{section.fields.map((field) => entry.content[field.key]).filter(Boolean).join(" · ") || "추가 설명 없음"}</p></div><div className="form-actions"><button className="outline-button" type="button" onClick={() => begin(section, entry)}><Pencil size={13} /> 수정</button><button className="outline-button danger-button" type="button" disabled={busy} onClick={() => void remove(entry.id)}><Trash2 size={13} /> 삭제</button></div></div>)}{draft?.entryType === section.type ? <EntryForm section={section} draft={draft} busy={busy} onChange={setDraft} onCancel={() => { setDraft(null); setEditingId(null); }} onSave={() => void save()} /> : <button type="button" className="resume-entry-add" onClick={() => begin(section)}><Plus size={16} /> {section.title} 추가</button>}</div>}</article>; })}</section>;
}

function EntryForm({ section, draft, busy, onChange, onCancel, onSave }: { section: Section; draft: ResumeEntryInput; busy: boolean; onChange: (next: ResumeEntryInput) => void; onCancel: () => void; onSave: () => void }) {
  const set = (key: string, value: string) => onChange({ ...draft, content: { ...draft.content, [key]: value } });
  return <div className="resume-entry-form"><label className="wide">항목 제목*<input value={draft.title} maxLength={255} onChange={(event) => onChange({ ...draft, title: event.target.value })} placeholder={section.type === "CAREER" ? "예: 백엔드 개발자" : "이력 항목 제목"} /></label><div className="form-fields">{section.fields.map((field) => <label className={field.kind === "textarea" ? "wide" : ""} key={field.key}>{field.label}{field.kind === "textarea" ? <textarea rows={3} value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)} /> : <input type={field.kind ?? "text"} value={draft.content[field.key] ?? ""} onChange={(event) => set(field.key, event.target.value)} />}</label>)}</div><div className="form-actions"><button className="outline-button" type="button" onClick={onCancel}>취소</button><button className="primary-button" type="button" disabled={busy} onClick={onSave}>{busy ? "저장 중…" : "저장"}</button></div></div>;
}
