import { BookOpen, ExternalLink, Search } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { DataStatePanel } from "../../../shared/components/DataStatePanel";
import { listRecommendedBooks, type RecommendedBook, type RecommendedBookPage } from "../api/bookRecommendationsApi";

const categories = [["ALL", "전체"], ["IT", "IT·개발"], ["DATA_AI", "데이터·AI"], ["CLOUD", "클라우드·DevOps"], ["SECURITY", "보안·네트워크"], ["CAREER", "IT 취업"], ["LANGUAGE", "영어"], ["BUSINESS", "비즈니스"]] as const;

export function BookRecommendationSection({ jobPostingId, requirementId, initialQuery = "" }: { jobPostingId: string | null; requirementId: string | null; initialQuery?: string }) {
  const [result, setResult] = useState<RecommendedBookPage | null>(null); const [status, setStatus] = useState<"loading" | "ready" | "error">("loading");
  const [queryDraft, setQueryDraft] = useState(initialQuery); const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState("ALL"); const [sort, setSort] = useState("relevance"); const [page, setPage] = useState(0);
  useEffect(() => { setStatus("loading"); void listRecommendedBooks({ jobPostingId, requirementId, query, category, sort, page }).then((data) => { setResult(data); setStatus("ready"); }).catch(() => { setResult(null); setStatus("error"); }); }, [jobPostingId, requirementId, query, category, sort, page]);
  const total = result?.total ?? 0; const pageCount = Math.max(1, Math.ceil(total / 30)); const safePage = Math.min(page, pageCount - 1); const pageStart = Math.max(0, Math.min(safePage - 3, pageCount - 7)); const pageNumbers = Array.from({ length: Math.min(7, pageCount) }, (_, index) => pageStart + index);
  const submit = (event: FormEvent) => { event.preventDefault(); setPage(0); setQuery(queryDraft.trim()); };
  return <section className="book-recommendation-section"><div className="certificate-opportunity-header"><h2>도서 추천</h2><span>알라딘 도서</span></div><p className="book-recommendation-guide">채용공고의 부족 기술을 학습 근거로 채울 수 있는 책을 찾아드려요.</p>
    <form className="opportunity-catalog-controls" onSubmit={submit}><input value={queryDraft} onChange={(event) => setQueryDraft(event.target.value)} placeholder="기술·도서명·저자 검색" aria-label="도서 검색" /><button type="submit" className="outline-button"><Search size={14} /> 검색</button><select value={sort} onChange={(event) => { setSort(event.target.value); setPage(0); }} aria-label="도서 정렬"><option value="relevance">관련도순</option><option value="title">가나다순</option><option value="published">최신순</option><option value="rating">평점순</option></select></form>
    <div className="certificate-field-filter" role="tablist" aria-label="도서 분야 필터">{categories.map(([value, label]) => <button type="button" key={value} className={category === value ? "field-chip active" : "field-chip"} onClick={() => { setCategory(value); setPage(0); }}>{label}</button>)}</div>
    {status === "loading" && <DataStatePanel state="loading" />}{status === "error" && <DataStatePanel state="error" emptyTitle="도서를 불러오지 못했습니다" emptyBody="알라딘 API 키 설정과 네트워크 상태를 확인한 뒤 다시 시도해 주세요." />}{status === "ready" && result && <>{!query && <div className="book-recommendation-context"><BookOpen size={16} /><span><strong>{result.recommendationKeyword}</strong> 학습 도서를 우선 추천합니다.{result.evidence && <small>공고 근거 · {result.evidence}</small>}</span></div>}{result.items.length === 0 ? <DataStatePanel state="empty" emptyTitle="해당 조건의 도서가 없습니다" emptyBody="검색어나 분야를 바꿔 다시 찾아보세요." /> : <div className="book-recommendation-grid">{result.items.map((book) => <BookCard key={book.isbn13 || book.link} item={book} />)}</div>}{total > 30 && <div className="opportunity-pagination" aria-label="도서 목록 페이지"><button type="button" aria-label="이전 페이지" disabled={safePage === 0} onClick={() => setPage(safePage - 1)}>‹</button>{pageNumbers.map((number) => <button type="button" key={number} className={number === safePage ? "active" : ""} onClick={() => setPage(number)}>{number + 1}</button>)}<button type="button" aria-label="다음 페이지" disabled={!result.hasMore} onClick={() => setPage(safePage + 1)}>›</button></div>}</>}</section>;
}
function BookCard({ item }: { item: RecommendedBook }) { return <article className="book-recommendation-card"><div className="book-cover">{item.coverUrl ? <img src={item.coverUrl} alt="" /> : <BookOpen size={32} />}</div><div className="book-recommendation-copy"><span className="book-category">{item.category || "도서"}</span><h3>{item.title}</h3><p>{[item.author, item.publisher, item.publishedAt].filter(Boolean).join(" · ")}</p>{item.description && <small>{item.description}</small>}<div className="skills">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="book-card-footer">{item.price > 0 && <span>{item.price.toLocaleString()}원</span>}<a href={item.link} target="_blank" rel="noreferrer">알라딘에서 보기 <ExternalLink size={13} /></a></div></div></article>; }
