package com.jobpilot.api.domain.community;

import com.jobpilot.api.domain.admin.AdminAccessService;
import com.jobpilot.api.domain.sentiment.client.SentimentAiClient;
import java.time.LocalDateTime;import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;
import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;

@Service public class CommunityService{
 private final JdbcTemplate db;private final AdminAccessService admins;
 public CommunityService(JdbcTemplate db,AdminAccessService admins){this.db=db;this.admins=admins;}
 public record Post(long id,long authorId,String author,String boardType,String title,String body,boolean serviceFeedback,boolean privatePost,String status,long views,long likes,long comments,boolean liked,boolean mine,LocalDateTime createdAt,LocalDateTime updatedAt){}
 public record PostPage(List<Post> items,long total,int page,int size,int totalPages){}
 public record Comment(long id,long postId,long authorId,String author,Long parentId,String body,long likes,boolean liked,boolean mine,LocalDateTime createdAt){}
 public record Input(String boardType,String title,String body,boolean serviceFeedback,boolean privatePost){}
 private String text(String v,int max){if(v==null||v.isBlank()||v.strip().codePointCount(0,v.strip().length())>max)throw bad("입력 길이를 확인하세요.");return v.strip();}
 private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
 private boolean admin(Long id){return id!=null&&admins.isAdmin(id);}
 public PostPage list(String type,Long member,int page,int size,String query,String sort){if(!List.of("FREE","QNA").contains(type)||page<0||size<1||size>100)throw bad("목록 조건이 올바르지 않습니다.");String order=switch(sort){case"POPULAR"->"p.view_count DESC,p.id DESC";case"LIKED"->"likes DESC,p.id DESC";default->"p.id DESC";};String q=query==null?"":query.strip();String where=" WHERE p.board_type=? AND p.status='PUBLIC' AND (p.private_post=FALSE OR p.author_member_id=? OR ?=TRUE) AND (?='' OR p.title LIKE CONCAT('%',?,'%') OR p.body LIKE CONCAT('%',?,'%'))";Object[] conditions={type,member,admin(member),q,q,q};Long total=db.queryForObject("SELECT COUNT(*) FROM community_posts p"+where,Long.class,conditions);String sql="SELECT p.*,m.nickname,(SELECT COUNT(*) FROM community_post_likes l WHERE l.post_id=p.id) likes,(SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.status='PUBLIC') comments, EXISTS(SELECT 1 FROM community_post_likes l WHERE l.post_id=p.id AND l.member_id=?) liked FROM community_posts p JOIN members m ON m.id=p.author_member_id"+where+" ORDER BY "+order+" LIMIT ? OFFSET ?";List<Object> args=new ArrayList<>();args.add(member);for(Object condition:conditions)args.add(condition);args.add(size);args.add(page*size);long count=total==null?0:total;return new PostPage(db.query(sql,(r,n)->post(r,member),args.toArray()),count,page,size,(int)Math.ceil(count/(double)size));}
 @Transactional public Post detail(long id,Long member){Map<String,Object> row=find(id);boolean can= !bool(row.get("private_post"))||eq(row.get("author_member_id"),member)||admin(member);if(!can)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"비공개 문의입니다.");if(db.update("INSERT IGNORE INTO community_post_views(post_id,member_id) VALUES (?,?)",id,member)==1)db.update("UPDATE community_posts SET view_count=view_count+1 WHERE id=?",id);return queryPost(id,member);}
 @Transactional public Post create(Long member,Input in){String type=text(in.boardType(),20);if(!List.of("FREE","QNA").contains(type))throw bad("게시판 종류가 올바르지 않습니다.");if(in.privatePost()&&!"QNA".equals(type))throw bad("비공개 글은 Q&A에서만 가능합니다.");String title=text(in.title(),200),body=text(in.body(),5000),hash=SentimentAiClient.contentHash(title+"\n"+body);boolean analyzable=!in.privatePost();long id=insert("INSERT INTO community_posts(author_member_id,board_type,title,body,service_feedback,private_post,content_hash,analysis_state,next_analysis_at) VALUES (?,?,?,?,?,?,?,?,?)",member,type,title,body,in.serviceFeedback(),in.privatePost(),hash,analyzable?"PENDING":"SKIPPED",analyzable?LocalDateTime.now():null);return queryPost(id,member);}
 @Transactional public Post update(long id,Long member,Input in){Map<String,Object> old=find(id);owner(old,member);String type=(String)old.get("board_type");if(!type.equals(in.boardType()))throw bad("게시판 종류는 변경할 수 없습니다.");String title=text(in.title(),200),body=text(in.body(),5000),hash=SentimentAiClient.contentHash(title+"\n"+body);boolean analyzable=!in.privatePost();db.update("UPDATE community_posts SET title=?,body=?,service_feedback=?,private_post=?,content_hash=?,analysis_state=?,analysis_attempts=0,next_analysis_at=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?",title,body,in.serviceFeedback(),in.privatePost(),hash,analyzable?"PENDING":"SKIPPED",analyzable?LocalDateTime.now():null,id);return queryPost(id,member);}
 @Transactional public void delete(long id,Long member){Map<String,Object> p=find(id);owner(p,member);db.update("UPDATE community_posts SET status='DELETED',next_analysis_at=NULL,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?",id);}
 @Transactional public boolean like(long id,Long member){find(id);int deleted=db.update("DELETE FROM community_post_likes WHERE post_id=? AND member_id=?",id,member);if(deleted==0)db.update("INSERT INTO community_post_likes(post_id,member_id) VALUES (?,?)",id,member);return deleted==0;}
 public List<Comment> comments(long postId,Long member){Map<String,Object> p=find(postId);if(bool(p.get("private_post"))&&!eq(p.get("author_member_id"),member)&&!admin(member))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"비공개 문의입니다.");return db.query("""
 SELECT c.*,m.nickname,(SELECT COUNT(*) FROM community_comment_likes l WHERE l.comment_id=c.id) likes,
 EXISTS(SELECT 1 FROM community_comment_likes l WHERE l.comment_id=c.id AND l.member_id=?) liked FROM community_comments c JOIN members m ON m.id=c.author_member_id
 WHERE c.post_id=? AND c.status='PUBLIC' ORDER BY COALESCE(c.parent_id,c.id),c.parent_id IS NOT NULL,c.id
 """,(r,n)->new Comment(r.getLong("id"),r.getLong("post_id"),r.getLong("author_member_id"),r.getString("nickname"),(Long)r.getObject("parent_id"),r.getString("body"),r.getLong("likes"),r.getBoolean("liked"),eq(r.getLong("author_member_id"),member),r.getTimestamp("created_at").toLocalDateTime()),member,postId);}
 @Transactional public Comment comment(long postId,Long member,Long parent,String body){Map<String,Object> post=find(postId);ensureCanRead(post,member);if(parent!=null){try{Map<String,Object> p=db.queryForMap("SELECT post_id,parent_id FROM community_comments WHERE id=? AND status='PUBLIC'",parent);if(((Number)p.get("post_id")).longValue()!=postId||p.get("parent_id")!=null)throw bad("대댓글은 한 단계만 작성할 수 있습니다.");}catch(org.springframework.dao.EmptyResultDataAccessException e){throw bad("상위 댓글을 찾을 수 없습니다.");}}long id=insert("INSERT INTO community_comments(post_id,author_member_id,parent_id,body) VALUES (?,?,?,?)",postId,member,parent,text(body,2000));return comments(postId,member).stream().filter(c->c.id()==id).findFirst().orElseThrow();}
 @Transactional public void deleteComment(long id,Long member){Map<String,Object> c=db.queryForMap("SELECT * FROM community_comments WHERE id=?",id);owner(c,member);db.update("UPDATE community_comments SET status='DELETED',updated_at=CURRENT_TIMESTAMP WHERE id=?",id);}
 @Transactional public Comment updateComment(long id,Long member,String body){Map<String,Object> c=db.queryForMap("SELECT * FROM community_comments WHERE id=? AND status='PUBLIC'",id);owner(c,member);db.update("UPDATE community_comments SET body=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",text(body,2000),id);return comments(((Number)c.get("post_id")).longValue(),member).stream().filter(x->x.id()==id).findFirst().orElseThrow();}
 @Transactional public boolean likeComment(long id,Long member){int d=db.update("DELETE FROM community_comment_likes WHERE comment_id=? AND member_id=?",id,member);if(d==0)db.update("INSERT INTO community_comment_likes(comment_id,member_id) VALUES (?,?)",id,member);return d==0;}
 @Transactional public void report(String target,long id,Long member,String reason){if(!List.of("POST","COMMENT").contains(target))throw bad("신고 대상이 올바르지 않습니다.");String table="POST".equals(target)?"community_posts":"community_comments";Integer exists=db.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE id=? AND status='PUBLIC'",Integer.class,id);if(exists==null||exists==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"신고 대상을 찾을 수 없습니다.");try{db.update("INSERT INTO community_reports(target_type,target_id,member_id,reason) VALUES (?,?,?,?)",target,id,member,text(reason,1000));}catch(org.springframework.dao.DuplicateKeyException e){throw new ResponseStatusException(HttpStatus.CONFLICT,"이미 신고했습니다.");}}
 public List<Map<String,Object>> adminSentiment(Long member){admins.requireAdmin(member);return db.queryForList("""
 SELECT p.id,p.board_type,p.title,p.created_at,a.polarity,a.positive_score,a.neutral_score,a.negative_score,a.model_version
 FROM community_posts p LEFT JOIN community_post_analyses a ON a.id=(SELECT a2.id FROM community_post_analyses a2 WHERE a2.post_id=p.id AND a2.content_hash=p.content_hash ORDER BY a2.analyzed_at DESC,a2.id DESC LIMIT 1)
 WHERE p.service_feedback=TRUE AND p.status<>'DELETED' ORDER BY p.id DESC LIMIT 100
 """);}
 public Map<String,Object> adminSummary(Long member){admins.requireAdmin(member);Map<String,Object> totals=db.queryForMap("""
  SELECT COUNT(*) feedbackCount,SUM(a.polarity='POSITIVE') positiveCount,SUM(a.polarity='NEUTRAL') neutralCount,
   SUM(a.polarity='NEGATIVE') negativeCount,SUM(a.polarity='MIXED') mixedCount,SUM(a.id IS NULL) pendingCount
  FROM community_posts p LEFT JOIN community_post_analyses a ON a.id=(SELECT a2.id FROM community_post_analyses a2 WHERE a2.post_id=p.id AND a2.content_hash=p.content_hash ORDER BY a2.analyzed_at DESC,a2.id DESC LIMIT 1)
  WHERE p.private_post=FALSE AND p.status='PUBLIC'
  """);return Map.of("summary",totals,"boards",List.of(boardSummary("FREE"),boardSummary("QNA")));}
 private Map<String,Object> boardSummary(String boardType){List<Map<String,Object>> rows=db.queryForList("SELECT p.id,p.title,p.body,p.created_at,a.polarity,a.positive_score,a.negative_score FROM community_posts p LEFT JOIN community_post_analyses a ON a.id=(SELECT a2.id FROM community_post_analyses a2 WHERE a2.post_id=p.id AND a2.content_hash=p.content_hash ORDER BY a2.analyzed_at DESC,a2.id DESC LIMIT 1) WHERE p.board_type=? AND p.private_post=FALSE AND p.status='PUBLIC' ORDER BY p.id DESC LIMIT 100",boardType);long positiveTerms=0,negativeTerms=0;for(Map<String,Object> row:rows){String content=row.get("title")+" "+row.get("body");long positive=countSignals(content,true),negative=countSignals(content,false);positiveTerms+=positive;negativeTerms+=negative;row.put("positiveTerms",positive);row.put("negativeTerms",negative);row.remove("body");}long positivePosts=rows.stream().filter(r->"POSITIVE".equals(r.get("polarity"))).count(),negativePosts=rows.stream().filter(r->"NEGATIVE".equals(r.get("polarity"))).count(),pending=rows.stream().filter(r->r.get("polarity")==null).count();Map<String,Object> result=new LinkedHashMap<>();result.put("boardType",boardType);result.put("postCount",rows.size());result.put("positivePostCount",positivePosts);result.put("negativePostCount",negativePosts);result.put("positiveTerms",positiveTerms);result.put("negativeTerms",negativeTerms);result.put("pendingCount",pending);result.put("recent",rows.stream().limit(5).toList());return result;}
 private long countSignals(String text,boolean positive){List<String> signals=positive?List.of("좋","만족","추천","감사","최고","편리","도움","훌륭","반갑","빠르"):List.of("불편","오류","실망","느리","최악","짜증","문제","불만","답답","고장");String lower=text==null?"":text.toLowerCase();long count=0;for(String signal:signals){int at=0;while((at=lower.indexOf(signal,at))>=0){count++;at+=signal.length();}}return count;}
 @Transactional public void moderate(Long admin,String target,long id,String action,String reason){admins.requireAdmin(admin);if(!List.of("POST","COMMENT").contains(target)||!List.of("HIDE","RESTORE","DELETE").contains(action))throw bad("관리 작업이 올바르지 않습니다.");String table="POST".equals(target)?"community_posts":"community_comments";String status="RESTORE".equals(action)?"PUBLIC":"DELETE".equals(action)?"DELETED":"HIDDEN";db.update("UPDATE "+table+" SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",status,id);db.update("INSERT INTO community_moderation_events(target_type,target_id,admin_member_id,action,reason) VALUES (?,?,?,?,?)",target,id,admin,action,text(reason,1000));}
 private Map<String,Object> find(long id){try{return db.queryForMap("SELECT * FROM community_posts WHERE id=? AND status<>'DELETED'",id);}catch(org.springframework.dao.EmptyResultDataAccessException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"게시글을 찾을 수 없습니다.");}}
 private void ensureCanRead(Map<String,Object> p,Long member){if(bool(p.get("private_post"))&&!eq(p.get("author_member_id"),member)&&!admin(member))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"비공개 문의입니다.");}
 private Post queryPost(long id,Long viewer){return db.queryForObject("SELECT p.*,m.nickname,(SELECT COUNT(*) FROM community_post_likes l WHERE l.post_id=p.id) likes,(SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.status='PUBLIC') comments,EXISTS(SELECT 1 FROM community_post_likes l WHERE l.post_id=p.id AND l.member_id=?) liked FROM community_posts p JOIN members m ON m.id=p.author_member_id WHERE p.id=?",(r,n)->post(r,viewer),viewer,id);}
 private Post post(java.sql.ResultSet r,Long viewer)throws java.sql.SQLException{return new Post(r.getLong("id"),r.getLong("author_member_id"),r.getString("nickname"),r.getString("board_type"),r.getString("title"),r.getString("body"),r.getBoolean("service_feedback"),r.getBoolean("private_post"),r.getString("status"),r.getLong("view_count"),r.getLong("likes"),r.getLong("comments"),r.getBoolean("liked"),eq(r.getLong("author_member_id"),viewer),r.getTimestamp("created_at").toLocalDateTime(),r.getTimestamp("updated_at").toLocalDateTime());}
 private long insert(String sql,Object...args){var key=new org.springframework.jdbc.support.GeneratedKeyHolder();db.update(c->{var p=c.prepareStatement(sql,java.sql.Statement.RETURN_GENERATED_KEYS);for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},key);Number id=key.getKey();if(id==null)throw new IllegalStateException("generated id missing");return id.longValue();}
 private void owner(Map<String,Object> row,Long member){if(!eq(row.get("author_member_id"),member))throw new org.springframework.security.access.AccessDeniedException("본인 작성물만 변경할 수 있습니다.");}private boolean eq(Object n,Long id){return n!=null&&id!=null&&((Number)n).longValue()==id;}private boolean bool(Object v){return Boolean.TRUE.equals(v)||v instanceof Number n&&n.intValue()!=0;}
}
