package com.jobpilot.api.domain.community;
import com.fasterxml.jackson.databind.ObjectMapper;import com.jobpilot.api.domain.sentiment.client.SentimentAiClient;import jakarta.annotation.*;import java.time.LocalDateTime;import java.util.*;import java.util.concurrent.*;import org.slf4j.*;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Component;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;
/** Analyzes only posts explicitly marked as service feedback; general forum talk remains SKIPPED. */
@Component @ConditionalOnProperty(name="app.sentiment.worker.enabled",havingValue="true") public class CommunitySentimentWorker{
 private static final Logger log=LoggerFactory.getLogger(CommunitySentimentWorker.class);private final JdbcTemplate db;private final SentimentAiClient ai;private final ObjectMapper json;private final TransactionTemplate tx;private final ScheduledExecutorService executor=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"community-sentiment");t.setDaemon(true);return t;});
 record Work(long id,long version,String hash,String text,int attempts){}
 public CommunitySentimentWorker(JdbcTemplate db,SentimentAiClient ai,ObjectMapper json,PlatformTransactionManager manager){this.db=db;this.ai=ai;this.json=json;this.tx=new TransactionTemplate(manager);}
 @PostConstruct void start(){executor.scheduleWithFixedDelay(this::batch,15,15,TimeUnit.SECONDS);}@PreDestroy void stop(){executor.shutdownNow();}
 private void batch(){try{for(int n=0;n<10;n++){Optional<Work>w=tx.execute(x->claim());if(w.isEmpty())break;analyze(w.get());}}catch(RuntimeException e){log.warn("Community sentiment batch deferred");}}
 private Optional<Work>claim(){db.update("UPDATE community_posts SET analysis_state='FAILED',next_analysis_at=NULL,version=version+1 WHERE analysis_state='PROCESSING' AND analysis_attempts>=5 AND next_analysis_at<=CURRENT_TIMESTAMP");var rows=db.query("SELECT id,version,content_hash,title,body,analysis_attempts FROM community_posts WHERE service_feedback=TRUE AND status='PUBLIC' AND analysis_state IN('PENDING','FAILED','PROCESSING') AND analysis_attempts<5 AND next_analysis_at<=CURRENT_TIMESTAMP ORDER BY next_analysis_at,id LIMIT 1",(r,n)->new Work(r.getLong(1),r.getLong(2),r.getString(3),r.getString(4)+"\n"+r.getString(5),r.getInt(6)+1));if(rows.isEmpty())return Optional.empty();Work w=rows.getFirst();int changed=db.update("UPDATE community_posts SET analysis_state='PROCESSING',analysis_attempts=analysis_attempts+1,next_analysis_at=DATE_ADD(CURRENT_TIMESTAMP,INTERVAL 2 MINUTE),version=version+1 WHERE id=? AND version=? AND service_feedback=TRUE AND status='PUBLIC'",w.id,w.version);return changed==1?Optional.of(new Work(w.id,w.version+1,w.hash,w.text,w.attempts)):Optional.empty();}
 private void analyze(Work w){try{var result=ai.analyze(w.text);if(result.isEmpty()||!w.hash.equals(result.get().contentHash())){fail(w);return;}var a=result.get();String emotions=json.writeValueAsString(a.emotions());tx.executeWithoutResult(x->{int changed=db.update("UPDATE community_posts SET analysis_state='COMPLETED',next_analysis_at=NULL,version=version+1 WHERE id=? AND version=? AND content_hash=? AND status='PUBLIC'",w.id,w.version,w.hash);if(changed==1)db.update("INSERT INTO community_post_analyses(post_id,content_hash,model_version,policy_version,polarity,positive_score,neutral_score,negative_score,emotions) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=id",w.id,w.hash,a.modelVersion(),a.policyVersion(),a.polarity().label(),a.polarity().positive(),a.polarity().neutral(),a.polarity().negative(),emotions);});}catch(Exception e){fail(w);}}
 private void fail(Work w){LocalDateTime next=w.attempts>=5?null:LocalDateTime.now().plusSeconds(30L<<(w.attempts-1));tx.executeWithoutResult(x->db.update("UPDATE community_posts SET analysis_state='FAILED',next_analysis_at=?,version=version+1 WHERE id=? AND version=? AND content_hash=? AND status='PUBLIC'",next,w.id,w.version,w.hash));}
}
